server:
  port: 8080

application:
  name: gateway
system:
  logging:
    file: /data/log/${spring.application.name}/${spring.application.name}.log
    format: "%date{yyyy-MM-dd HH:mm:ss,SSS} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"

spring:
  application:
    name: ${application.name}
  main:
    allow-bean-definition-overriding: true
  cloud:
    util:
      enabled: true
    discovery:
      enabled: true
    nacos:
      config:
        server-addr: "nacos.local.dev.xyz:8848"
        namespace: ed10926a-05e2-4990-95e5-d213e3ac9f73
        file-extension: yaml
        group: DEV_GROUP
        refresh-enabled: true
        enabled: true
      discovery:
        server-addr: "nacos.local.dev.xyz:8848"
        namespace: ed10926a-05e2-4990-95e5-d213e3ac9f73
        group: DEV_GROUP
    compatibility-verifier:
      enabled: false
#    inetutils:
#      default-hostname: localhost
#      default-ip-address: 0.0.0.0

shenyu:
#  spring-cloud-cache:
#    enabled: true
  sync:
    websocket:
#      urls: ws://shenyu-admin.local.dev.xyz:9095/websocket  # shenyu-admin 地址
#      allowOrigin: ws://shenyu-admin.local.dev.xyz:9195
      urls: ws://127.0.0.1:9095/websocket  # shenyu-admin 地址
      allowOrigin: ws://127.0.0.1:9195
  netty:
    http:
      webServerFactoryEnabled: true
      selectCount: 16
      workerCount: 256

logging.file.name: ${system.logging.file}
logging.pattern.file: "%date{yyyy-MM-dd HH:mm:ss,SSS} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"
logging.pattern.console: "%date{yyyy-MM-dd HH:mm:ss,SSS} %level [%thread] [%X{trace_id}] [%logger{10}#%method:%line] - %msg%n%throwable"

logging:
  level:
    root: info
    org.apache.shenyu: debug



